package vistas;
import java.util.HashSet;
import model.Alumno;
import model.Materia;
import javax.swing.JOptionPane;


/**
 *
 * @author santi
 */
public class VistaInscripcion extends javax.swing.JInternalFrame {
     private HashSet<Alumno> alumnosSet; 
     private HashSet<Materia> materiasSet;

    public VistaInscripcion(HashSet<Alumno> alumnosSet, HashSet<Materia> materiasSet) {
        initComponents();
        
        this.alumnosSet = alumnosSet; 
        this.materiasSet = materiasSet;
        
        cargarAlumnos(); 
        cargarMaterias();
        
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>()); 
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>());
    }
    
    private void cargarAlumnos() { 
        jComboBox1.removeAllItems(); 
        for (Alumno alumno: alumnosSet){ 
         jComboBox1.addItem(alumno.toString());      
        } 
    } 
    
    private void cargarMaterias() { 
        jComboBox2.removeAllItems(); 
        for (Materia materias: materiasSet) {
        jComboBox2.addItem(materias.toString()); 
        } 
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Elija una materia:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Elija un alumno:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Inscribir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 198, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose(); //Cerrar solo este JinternalFrame
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String alumnoStr= (String) jComboBox1.getSelectedItem();
        String materiaStr= (String) jComboBox2.getSelectedItem();
        
        Alumno alumnoSeleccionado= null;
        Materia materiaSeleccionada= null; 
        
        // Buscar el alumno real en el set
    for (Alumno alumno : alumnosSet) { 
        if (alumno.toString().equals(alumnoStr)) { 
            alumnoSeleccionado = alumno; 
            break; 
        } 
    }

    // Buscar la materia real en el set
    for (Materia materia : materiasSet) { 
        if (materia.toString().equals(materiaStr)) { 
            materiaSeleccionada = materia; 
            break; 
        } 
    }

    // Validaciones
    if (alumnoSeleccionado == null || materiaSeleccionada == null) {
        JOptionPane.showMessageDialog(this, 
                "Debe seleccionar un alumno y una materia válida.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
    } else {
        // Verificar si ya estaba inscripto
        if (alumnoSeleccionado.getMaterias().contains(materiaSeleccionada)) {
            JOptionPane.showMessageDialog(this, 
                    "El alumno ya estaba inscripto en esa materia.", 
                    "Aviso", 
                    JOptionPane.WARNING_MESSAGE);
        } else {
            alumnoSeleccionado.inscribirMateria(materiaSeleccionada);
            JOptionPane.showMessageDialog(this, 
                    "El alumno " + alumnoSeleccionado.getNombre() + 
                    " fue inscripto en " + materiaSeleccionada.getNombreMateria(), 
                    "Inscripción exitosa", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables

    
}
